# Generated by Django 4.2.2 on 2023-06-21 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=280)),
                ('description', models.CharField(max_length=1000)),
                ('goal', models.FloatField(default=1000.0, validators=[django.core.validators.MaxValueValidator(100000, 0), django.core.validators.MinValueValidator(10.0)])),
                ('current', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('location', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.fundraiser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
