# Generated by Django 4.2.2 on 2023-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
