# Generated by Django 4.2.2 on 2023-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
