# Generated by Django 4.2.2 on 2023-06-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fundraiser_lat_fundraiser_long'),
        ('main_app', '0004_alter_profile_latitude_alter_profile_longitude'),
    ]

    operations = [
    ]
