# Generated by Django 4.2.2 on 2023-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_merge_20230622_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='distance_from_user',
            field=models.FloatField(default=0.0),
        ),
    ]
