# Generated by Django 4.2.2 on 2023-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_fundraiser_distance_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_fundrs',
            field=models.CharField(default=''),
        ),
    ]
