# Generated by Django 4.2.2 on 2023-06-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_fundraiser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_fundrs',
        ),
    ]
