# Generated by Django 4.2.2 on 2023-06-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_content'),
        ('main_app', '0009_remove_profile_saved_fundrs'),
    ]

    operations = [
    ]
