# Generated by Django 4.2.2 on 2023-06-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='http://localhost:8000/static/main_app/home_pic.png', max_length=200),
        ),
    ]
