# Generated by Django 4.2.2 on 2023-06-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_url_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='image',
            field=models.CharField(default='http://localhost:8000/static/main_app/home_pic.png', max_length=200),
        ),
    ]
