# Generated by Django 4.2.2 on 2023-06-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20230623_1556'),
        ('main_app', '0016_alter_fundraiser_image'),
    ]

    operations = [
    ]
