# Generated by Django 4.2.2 on 2023-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_merge_20230625_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catchment',
            field=models.FloatField(default=100),
        ),
    ]
